name: pysubsurface
channels:
- defaults
- conda-forge
dependencies:
- python>=3.6.4
- pip
- numpy>=1.15.0
- scipy
- matplotlib
- pandas
- seaborn
- scikit-learn
- pylops
- verde
- ipython
- jupyter
- pytest
- pytest-runner
- Sphinx
- numpydoc
- pip:
  - lasio
  - segyio
  - matplotlib-scalebar
  - shapely
  - descartes
  - pyyaml
  - Deprecated
  - sphinx-rtd-theme
  - sphinx-gallery
  - nbsphinx
  - image
  - git+https://github.com/cjohnson318/geostatsmodels.git
